version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    steps:
      - checkout
      - run:
          name: Run Hello test
          command: |
            bash src/test_hello.sh
      - run:
          name: Run Goodbye test
          command: |
            bash src/test_goodbye.sh
        parallelism: 4
workflows:
  version: 2
  test:
    jobs:
      - test