version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            exit 1
workflows:
  version: 2
  test:
    jobs:
      - test