version: 2
jobs:
  test:
    docker:
      - image: circleci/node
    parallelism: 4
    steps:
      - checkout
      - run:
          name: Run tests
          command: |
            circleci tests glob "test_hello.sh" "test_goodbye.sh" | xargs -n 1 echo
workflows:
  version: 2
  test:
    jobs:
      - test